### ISSUE TITLE
ubuntu 16.04 web only install, 500 apache error on :443

### ISSUE THREAD

**Issue by rspierz** [TravisFSmith/SweetSecurity#30]
New install

Apache error log shows this:

```
mod_wsgi (pid=2308): Target WSGI script '/var/www/webapp/webapp.wsgi' cannot be loaded as Python module.
[Tue Nov 21 20:51:39.182414 2017] [wsgi:error] [pid 2308:tid 140455865923328] [client 10.0.0.10:38378] mod_wsgi (pid=2308): Exception occurred processing WSGI script '/var/www/webapp/webapp.wsgi'.
[Tue Nov 21 20:51:39.182470 2017] [wsgi:error] [pid 2308:tid 140455865923328] [client 10.0.0.10:38378] Traceback (most recent call last):
[Tue Nov 21 20:51:39.184855 2017] [wsgi:error] [pid 2308:tid 140455865923328] [client 10.0.0.10:38378]   File "/var/www/webapp/webapp.wsgi", line 7, in <module>
[Tue Nov 21 20:51:39.185055 2017] [wsgi:error] [pid 2308:tid 140455865923328] [client 10.0.0.10:38378]     from webapp import create_app
[Tue Nov 21 20:51:39.185111 2017] [wsgi:error] [pid 2308:tid 140455865923328] [client 10.0.0.10:38378]   File "/var/www/webapp/webapp/__init__.py", line 18, in <module>
[Tue Nov 21 20:51:39.185259 2017] [wsgi:error] [pid 2308:tid 140455865923328] [client 10.0.0.10:38378]     class ConfigClass(object):
[Tue Nov 21 20:51:39.185314 2017] [wsgi:error] [pid 2308:tid 140455865923328] [client 10.0.0.10:38378]   File "/var/www/webapp/webapp/__init__.py", line 24, in ConfigClass
[Tue Nov 21 20:51:39.185399 2017] [wsgi:error] [pid 2308:tid 140455865923328] [client 10.0.0.10:38378]     MAIL_PORT =           int(os.getenv('MAIL_PORT',            ''))
[Tue Nov 21 20:51:39.185490 2017] [wsgi:error] [pid 2308:tid 140455865923328] [client 10.0.0.10:38378] ValueError: invalid literal for int() with base 10: ''

```

**Comment by rspierz** [comment]
Fixed this issue, a few mail variables were missing.

However, now that everything is up and running. My Kibana dashboards do not display any data. There are shards with no data.

`.kibana               0 p STARTED    40 94.2kb 127.0.0.1 vbkTBMf
.kibana               0 r UNASSIGNED                     
sweet_security        4 p STARTED     2 18.2kb 127.0.0.1 vbkTBMf
sweet_security        4 r UNASSIGNED                     
sweet_security        3 p STARTED     0   191b 127.0.0.1 vbkTBMf
sweet_security        3 r UNASSIGNED                     
sweet_security        1 p STARTED     0   191b 127.0.0.1 vbkTBMf
sweet_security        1 r UNASSIGNED                     
sweet_security        2 p STARTED     0   191b 127.0.0.1 vbkTBMf
sweet_security        2 r UNASSIGNED                     
sweet_security        0 p STARTED     0   191b 127.0.0.1 vbkTBMf
sweet_security        0 r UNASSIGNED                     
sweet_security_alerts 4 p STARTED     0   191b 127.0.0.1 vbkTBMf
sweet_security_alerts 4 r UNASSIGNED                     
sweet_security_alerts 3 p STARTED     0   191b 127.0.0.1 vbkTBMf
sweet_security_alerts 3 r UNASSIGNED                     
sweet_security_alerts 2 p STARTED     0   191b 127.0.0.1 vbkTBMf
sweet_security_alerts 2 r UNASSIGNED                     
sweet_security_alerts 1 p STARTED     0   191b 127.0.0.1 vbkTBMf
sweet_security_alerts 1 r UNASSIGNED                     
sweet_security_alerts 0 p STARTED     0   191b 127.0.0.1 vbkTBMf
sweet_security_alerts 0 r UNASSIGNED                     
tardis                4 p STARTED     0   191b 127.0.0.1 vbkTBMf
tardis                4 r UNASSIGNED                     
tardis                3 p STARTED     0   191b 127.0.0.1 vbkTBMf
tardis                3 r UNASSIGNED                     
tardis                2 p STARTED     0   191b 127.0.0.1 vbkTBMf
tardis                2 r UNASSIGNED                     
tardis                1 p STARTED     0   191b 127.0.0.1 vbkTBMf
tardis                1 r UNASSIGNED                     
tardis                0 p STARTED     0   191b 127.0.0.1 vbkTBMf
tardis                0 r UNASSIGNED                     
`
