### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '/opt/nsm/bro/etc/node.cfg'

### ISSUE THREAD

**Issue by clarancedriver** [TravisFSmith/SweetSecurity#37]
Any idea why the node.cfg is not getting built?

Traceback (most recent call last):
  File "setup.py", line 257, in <module>
    bro.install(chosenInterface, esServer)
  File "/home/pi/Repos/SweetSecurity/install/bro.py", line 45, in install
    shutil.move('/opt/nsm/bro/etc/node.cfg','/opt/nsm/bro/etc/node.orig')
  File "/usr/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/opt/nsm/bro/etc/node.cfg'

**Comment by marcellos** [comment]
This seems like a duplicate of #25 
Check the solution there or check the FAQ

**Comment by jouellnyc** [comment]
Yes, I got the same and #25 resolved it.
